# Site settings
title: LaBelleCompagnie
email: LaBelleCompagnie2017@gmail.com
url: https://example.github.io
description: "C'est officiel, le cannabis est maintenant un marché évalué à plus de $20 million de Dollars, en Amérique du Nord seulement.Tandis que le monde se préparent tranquilement à ce changement, que sait-on vraiment de cette plante ? 
En quoi pourrait-elle nous être bénéfique ou au contraire, maléfique ? 
Seriez-vous surpris de savoir que celle-ci peut vous faire économiser sur votre facture de chauffage ?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0a961d'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
